# Importing Numpy module

In [1]:
import numpy as np

#### Numpy arrays - can be created with the help of np.array()

In [2]:
kanto = np.array([73,67,43])

In [3]:
kanto

array([73, 67, 43])

In [5]:
weights = np.array([0.5,0.7,0.4])
weights

array([0.5, 0.7, 0.4])

In [6]:
type(kanto)

numpy.ndarray

In [7]:
type(weights)

numpy.ndarray

#### Just like arrays, array has indexing feature

In [10]:
kanto[0]

73

In [11]:
weights[0]

0.5

# Operation on Numpy arrays

In [12]:
# dot product
np.dot(kanto,weights)

100.60000000000001

np.dot() is smilar to the below one

In [13]:
(kanto*weights).sum()

100.60000000000001

Lets compare lists with numpy array in terms of speed

In [14]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))

In [19]:
# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [22]:
%%time
result=0
for i,j in zip(arr1,arr2):
    result+=(i*j)
result

Wall time: 172 ms


833332333333500000

In [23]:
%%time
#using np.dot()
np.dot(arr1_np,arr2_np)

Wall time: 999 µs


-1942957984

## Multidimensional Array

In [24]:
climate_data = np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70] ])

In [25]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [26]:
# 2D array (matrix)
climate_data.shape

(5, 3)

In [27]:
weights

array([0.5, 0.7, 0.4])

In [28]:
#1D array
weights.shape

(3,)

In [35]:
#3D array
arr3 = np.array(
[[
    [11,12,13],
    [13,14,15] ],
[
    [15,16,17],
    [17,18,19]
    
] ] )

In [36]:
arr3

array([[[11, 12, 13],
        [13, 14, 15]],

       [[15, 16, 17],
        [17, 18, 19]]])

In [37]:
arr3.shape

(2, 2, 3)

All the lements in a numpy array have the same datatype. You can check the datatype of an array using .dtype property

In [38]:
weights.dtype

dtype('float64')

In [39]:
climate_data.dtype

dtype('int32')

In [40]:
arr3.dtype

dtype('int32')

In [41]:
# Matrix multiplication using np.matmul()
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [42]:
weights

array([0.5, 0.7, 0.4])

In [43]:
np.matmul(climate_data,weights)

array([100.6, 132.7, 160.5,  95.9, 129.7])

In [44]:
# or you can do matrix multiplication using @ symbol
climate_data @ weights

array([100.6, 132.7, 160.5,  95.9, 129.7])

## Reading data from csv file into numpy array


In [45]:
from urllib.request import urlretrieve
urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1a4f864fe08>)

In [46]:
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [47]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [48]:
climate_data.shape

(10000, 3)

In [49]:
weights = np.array([0.3,0.2,0.5])

In [50]:
yields = climate_data @ weights

In [51]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [52]:
yields.shape

(10000,)

### Concatenation

Let's add the yields to climate_data as a fourth column using the np.concatenate function

In [53]:
climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis=1)

In [54]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [55]:
# save the results back to the climate_results.txt
np.savetxt('climate_results.txt',climate_results,fmt='%.2f',delimiter=',',header='temperature,rainfall,humidity,yield_apples',comments='')

## Arithmetic Operations and Broadcasting and Comparison

Numpy arrays support arithmetic operators like +, -, *, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

In [56]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]])

In [57]:
arr3 = np.array([[11,12,13,14],[15,16,17,18],[19,11,12,13]])

In [58]:
# add a scalar
arr2+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [59]:
# Elementwise subtraction
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [61]:
# division by scalar
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [62]:
# Elementwise multiplication
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [63]:
# Modulus with scalar
arr2%4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

## Array Broadcasting

Numpy arrays also support broadcasting, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works

In [64]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [65]:
arr2.shape

(3, 4)

In [71]:
arr3 = np.array([10,20,30,40])
arr3.shape

(4,)

In [72]:
arr2+arr3

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [19, 21, 32, 43]])

Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

In [73]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([1,2])
ar1+ar2

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

# Array Comparison

Numpy arrays also support comparison operations like ==, !=, > etc. The result is an array of booleans.

In [74]:
arr1 = np.array([[1,2,3], [3,4,5]])
arr2 = np.array([[2,2,3], [1,2,5]])

In [75]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [76]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [77]:
arr1>=arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [81]:
(arr1<arr2)

array([[ True, False, False],
       [False, False, False]])

Array comparison is frequently used to count the number of equal elements in two arrays using the sum method. Remember that True evaluates to 1 and False evaluates to 0 when booleans are used in arithmetic operations.

In [79]:
(arr1 == arr2).sum()

3

# Array indexing and slicing

In [82]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])




In [83]:
arr3.shape

(3, 2, 4)

In [85]:
arr3[2,0,2]

81.0

In [86]:
#subarray using ranges
arr3[1:,0:1,:3]

array([[[15., 16., 17.]],

       [[98., 32., 81.]]])

In [87]:
# Mixing indices and ranges
arr3[1:,1,3]

array([18., 43.])

In [88]:
#mixing indices and ranges
arr3[1:,1,:3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [89]:
# using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [90]:
arr3[0]

array([[11., 12., 13., 14.],
       [13., 14., 15., 19.]])

In [93]:
arr3[0,0]

array([11., 12., 13., 14.])

In [95]:
arr3[0,0,0]

11.0

Note : If your using too many notations, you will get an error

# Other ways of creating numpy arrays

In [96]:
# All zeros
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [97]:
# All ones
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [104]:
# Identity matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [105]:
# Random vector
np.random.rand(5)

array([0.62037955, 0.93799003, 0.42124   , 0.8831611 , 0.27934148])

In [106]:
np.random.rand(2,3)

array([[0.46915195, 0.52695393, 0.58601649],
       [0.358474  , 0.10701313, 0.47972647]])

In [107]:
# Random matrix
np.random.randn(2,3)

array([[-0.17937199, -0.50460698,  0.66422857],
       [-1.02932249, -0.40475224,  0.88196132]])

Note : numpy.random.randn generates samples from the normal distribution, while numpy.random.rand from a uniform distribution (in the range [0,1]).

In [108]:
# Fixed value
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [110]:
# Range with start, end and step
np.arange(3,99,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96])

In [111]:
# Equally spaced numbers in a range
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

Note : The above function says generate 9 numbers between 3 to 27 with equally spaced